server {
    listen 80;
    server_name localhost;

    # La ruta base de nuestro frontend
    root /usr/share/nginx/html;
    
    # Archivo por defecto a buscar cuando se entra a '/'
    index index.html;

    # 1. Configuración de rutas (El Fix del 404)
    location / {
        # Si alguien entra a una ruta como /src/views/login.html, lo carga directamente.
        # Si entra a /login (sin .html) buscará si existe un archivo con ese nombre.
        # Si no encuentra nada, te redirige al index.html principal.
        try_files $uri $uri/ $uri.html /index.html;
    }

    # 2. Archivos estáticos (CSS, Imágenes)
    # Le decimos a Nginx que cargue esto rápido y lo mantenga en caché.
    location /public/ {
        # Para evitar problemas de caché durante el desarrollo, lo apagamos temporalmente.
        # En producción cambiaríamos esto a "expires max;"
        add_header Cache-Control "no-cache, must-revalidate";
        expires off;
    }

    # 3. Archivos JavaScript
    # Mismo trato para el JS, para que siempre veas los cambios recientes
    location /src/js/ {
        add_header Cache-Control "no-cache, must-revalidate";
        expires off;
    }

    # Manejo de errores internos para que no muestre la pantalla fea de Nginx
    error_page 404 /index.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
